services:
  # --- Sub-Store 服务 ---
  sub-store:
    image: xream/sub-store
    container_name: sub-store
    restart: always
    environment:
      - SUB_STORE_FRONTEND_BACKEND_PATH=/CKg3abstVnOeRpm1aB5G
    ports:
      - "3001:3001"
    volumes:
      - sub-store-data:/opt/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001" ]
      interval: 30s
      timeout: 5s
      retries: 3
  # --- Watchtower 自动更新守护 ---
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # 访问 Docker API
    command: --cleanup --schedule "0 */4 * * *"   # 每 4 小时检测更新并清理旧镜像

# --- 持久化卷定义 ---
volumes:
  sub-store-data:
    name: sub-store-data